config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'static#index'
  resources :products do
    resources :reviews
  end
  get '/admin_page' => 'admin#users'
  get '/edit_user/:id' => 'admin#edit_user'
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_condition)
    conditions = warden_condition.dup
    login = conditions.delete(:login)
    where(conditions).where(
      ['lower(username) = :value OR lower(email) = :value',
       { value: login.strip.downcase }]
    ).first
  end

  def validate_username
    errors.add(:username, :invalid) if Admin.where(email: username).exists?
  end
  validates :username, presence: :true, uniqueness: { case_sensitive: false }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  scope :most_reviewed, lambda {
                          select('products.*, count(reviews.id) as reviews_count')
                            .joins(:reviews)
                            .group('products.id')
                            .order('reviews_count DESC')
                            .limit(1)
                        }

  scope :usa, -> { where("country_of_origin ilike 'Usa'").or(Product.where("country_of_origin ilike '%united states%'")) }

  scope :recent_products, -> { order(created_at: :desc).limit(3) }

  before_save(:titleize_product, :titleize_country)
  has_many :reviews, dependent: :destroy
  validates :name, :cost, :country_of_origin, presence: true

  private

  def titleize_product
    self.name = name.titleize
  end

  def titleize_country
    self.country_of_origin = country_of_origin.titleize
  end
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, length: { maximum: 250, minumum: 50 }, presence: true
  validates :rating, numericality: { greater_than: 0, less_than_or_equal_to: 5 }, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_condition)
    conditions = warden_condition.dup
    login = conditions.delete(:login)
    where(conditions).where(
      ['lower(username) = :value OR lower(email) = :value',
       { value: login.strip.downcase }]
    ).first
  end

  def validate_username
    errors.add(:username, :invalid) if User.where(email: username).exists?
  end

  validates :username, presence: :true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def authorize_admin_user
    if !current_user && !current_admin
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_back(fallback_location: root_path)
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[username email password password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in,
                                      keys: %i[login password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[username email password_confirmation current_password])
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :authenticate_admin!, except: %i[index show]
  before_action :set_product, only: %i[show edit update destroy]
  def index
    @top_product = Product.most_reviewed.first
    @product_search = Product.where("name ilike '%#{params[:search]}%'").uniq
    @products = Product.all
    @page_products = Kaminari.paginate_array(@products).page(params[:page]).per(10)
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Product successfully added!'
      redirect_to products_path
    else
      flash[:alert] = 'Error adding product'
      render :new
    end
  end

  def edit
    render :edit
  end

  def show
    render :show
  end

  def update
    if @product.update(product_params)
      flash[:notice] = 'Product successfully updated!'
      redirect_to products_path
    else
      flash[:alert] = 'Error updating product'
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:notice] = 'Product successfully deleted!'
    else
      flash[:alert] = 'Error deleting product'
    end
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :authorize_admin_user, only: %i[new create]
  before_action :authenticate_admin!, only: %i[edit destroy]
  before_action :set_product, except: %i[update destroy]
  before_action :set_review, only: %i[show edit update destroy]

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = 'Review successfully added!'
      redirect_to product_path(@product)
    else
      flash[:alert] = 'Error adding review'
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end

  def set_product
    @product = Product.find(params[:product_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/controllers/static_controller.rb
# frozen_string_literal: true

class StaticController < ApplicationController
  def index
    @top_product = Product.most_reviewed.first
    @product_search = Product.where("name ilike '%#{params[:search]}%'").uniq
    @products = Product.all
    render :index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/static_helper.rb
# frozen_string_literal: true

module StaticHelper
end

app/views/admin/edit_user.html.erb
<h2><%= @user.username %></h2>

<h3>User Email:</h3>
<h4><%= @user.email %></h4>

<%= button_to "Cancel account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete %>

app/views/admin/users.html.erb
<% if @users.any? %>
<h2>There are <%= @users.count %> active users.</h2>
  <% @users.each do |user| %>
  <ul>
  <li><%= user.username %></li>
  <li><%= user.email %></li>
</ul>
  <% end %>
<% else %>
<p>There are no users yet.</p>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
<h4><%= f.label :name %></h4>
<%= f.text_field :name %>
<h4><%= f.label "Cost" %></h4>
<%= f.number_field :cost, step: 0.01 %>
<h4><%= f.label "Country of Origin" %></h4>
<%= f.text_field :country_of_origin %>
<p><%= f.submit :Submit, class: 'btn btn-primary' %></p>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
<% if current_user %>
  <%= f.hidden_field :author, value: current_user.username %>
  <% elsif current_admin %>
  <%= f.hidden_field :author, value: current_admin.username %>
  <% else %>
  <h4><%= f.label "Author Name"%></h4>
  <%= f.text_area :author %>
  <% end %>
  <h4><%= f.label "Review"%></h4>
  <%= f.text_area :content_body %>
  <h4><%= f.label "Rating"%></h4>
  <%= f.number_field :rating, in: 1..5 %>
  <br>
  <br>
  <p><%= f.submit :Submit, class: 'btn btn-primary' %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marios Special Foods</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="jumbotron">
    <div class="opaque">
      <h1>Mario's Specialty Foods</h1>
    </div>
  </div>

  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Products", products_path, :class => "nav-link" %>
        </li>
        <% if current_admin %>
        <li class="nav-item active">
          <%= link_to "Add a product", new_product_path, :class => "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
    <div class="mx-auto order-0">
      <%= link_to "MARIO'S", root_path, :class => "navbar-brand mx-auto" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Profile", edit_user_registration_path, :class => "nav-link my-2 my-sm-0" %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => "nav-link my-2 my-sm-0" %>
        </li>
        <% else %>
        <li class="nav-item active">
          <%= link_to "Sign in", new_user_session_path, :class => "nav-link my-2 my-sm-0" %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="container">
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </div>
  <br><br><br><br><br>
  <nav class="navbar navbar-dark bg-dark navbar-sticky-bottom">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <% if current_admin %>

        <%= link_to "Admin Console", admin_root_path, :class => "nav-link my-2 my-sm-0" %>
      </li>
      <li class="nav-item">
        <%= link_to "Admin Logout", destroy_admin_session_path, :method => :delete, :class => "nav-link my-2 my-sm-0" %>
        <% else %>
        <%= link_to "Admin Login",new_admin_session_path, :class => "nav-link" %>
        <% end %>
      </li>
    </ul>
  </nav>
</body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<div class="row">

  <div class="col-md-6">
    <h2>Products from the USA:</h2>
    <% if @products.usa.any? %>
      <ul>
        <% @products.usa.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
      </ul>
    <% else %>
      <p>There are no US products yet.</p>
    <% end %>
    <h2>Search for a product:</h2>
    <%= form_tag(products_path, method: :get) do %>
    <%= text_field_tag :search, '', placeholder: 'Enter search term...' %>
    <%= submit_tag ("search"), :class => 'btn btn-info' %>
  <% end %>

  <% if (@product_search != nil) && (@product_search.length != Product.all.length)  %>
    <ul>
      <% @product_search.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-6">
    <h2>All Products</h2>
    <% if @page_products.any? %>
      <ul>
        <% @page_products.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
      </ul>
    <% else %>
      <p>There are no more products.</p>
    <% end %>
    <%= paginate @page_products %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h4 class="butt"><%= link_to 'New Product', new_product_path %></h4>
  </div>
</div>

app/views/products/new.html.erb
<h1>new product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<div class="row">

  <div class="col-md-6 right">
    <h1 class="title"><%= @product.name %></h1>
    <% if current_admin %>
      <p><%= link_to "Edit", edit_product_path(@product) %>|<%= link_to "Delete", product_path(@product), :data => {:confirm => "Are you sure?", :method => "delete"} %>
      <% end %>
      <h3>Cost: $<%= @product.cost %></h3>
      <h3>Country or origin:
        <%= @product.country_of_origin %></h3>
      <p class="btn btn-info"><%= link_to "Add a review", new_product_review_path(@product) %></p>

    </div>

    <div class="col-md-6">

      <h2>Product reviews:</h2>
      <% if @product.reviews.any? %>
        <% @product.reviews.each do |review| %>
          <div class="card">

            <h4>
              By:
              <%= review.author %>
              on
              <%=review.created_at %></h4>
            <h4><%= review.rating %>
              STARS</h4>
            <hr>
            <ul>
              <li>
                <%= review.content_body %>
              </li>
            </ul>

          </div>
        <% end %>
      <% else %>
        <p>No reviews are listed for this product.</p>
      <% end %>

    </div>

  </div>
  <hr>

app/views/reviews/new.html.erb
<h1>New Review:</h1>

<%= render "layouts/review_form" %>